### ISSUE TITLE
Error when building for MacOS

### ISSUE THREAD

**Issue by slavingia** [wassimj/Topologic#42]
```
(topologic_py310) ➜  TopologicPythonBindings git:(main) ✗ python build_macos.py

Processing /Users/sahil/code/Topologic/TopologicPythonBindings
  Running command python setup.py egg_info
  running egg_info
  creating /private/var/folders/jg/8nz0xtdx23x4l7fvjqkf0n5c0000gn/T/pip-pip-egg-info-70w37xcj/topologic.egg-info
  writing /private/var/folders/jg/8nz0xtdx23x4l7fvjqkf0n5c0000gn/T/pip-pip-egg-info-70w37xcj/topologic.egg-info/PKG-INFO
  writing dependency_links to /private/var/folders/jg/8nz0xtdx23x4l7fvjqkf0n5c0000gn/T/pip-pip-egg-info-70w37xcj/topologic.egg-info/dependency_links.txt
  writing top-level names to /private/var/folders/jg/8nz0xtdx23x4l7fvjqkf0n5c0000gn/T/pip-pip-egg-info-70w37xcj/topologic.egg-info/top_level.txt
  writing manifest file '/private/var/folders/jg/8nz0xtdx23x4l7fvjqkf0n5c0000gn/T/pip-pip-egg-info-70w37xcj/topologic.egg-info/SOURCES.txt'
  reading manifest file '/private/var/folders/jg/8nz0xtdx23x4l7fvjqkf0n5c0000gn/T/pip-pip-egg-info-70w37xcj/topologic.egg-info/SOURCES.txt'
  writing manifest file '/private/var/folders/jg/8nz0xtdx23x4l7fvjqkf0n5c0000gn/T/pip-pip-egg-info-70w37xcj/topologic.egg-info/SOURCES.txt'
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: topologic
  Running command python setup.py bdist_wheel
  running bdist_wheel
  running build
  running build_py
  running build_ext
  INFO:build:syscmd: running subprocess: ['cmake', '-S', '/Users/sahil/code/Topologic/TopologicPythonBindings/..', '-G', 'Ninja', '-B', 'build/temp.macosx-10.9-x86_64-cpython-310/cmake-build-release', '-DCMAKE_BUILD_TYPE=Release', '-DTOPOLOGICCORE_BUILD_SHARED=OFF']
  -- The CXX compiler identification is Clang 14.0.6
  -- Detecting CXX compiler ABI info
  -- Detecting CXX compiler ABI info - done
  -- Check for working CXX compiler: /Users/sahil/opt/anaconda3/envs/topologic_py310/bin/x86_64-apple-darwin13.4.0-clang++ - skipped
  -- Detecting CXX compile features
  -- Detecting CXX compile features - done
  -- pybind11 v2.10.1
  -- Configuring done (5.8s)
  -- Generating done (0.0s)
  -- Build files have been written to: /Users/sahil/code/Topologic/TopologicPythonBindings/build/temp.macosx-10.9-x86_64-cpython-310/cmake-build-release
  INFO:build:syscmd: running subprocess: ['cmake', '--build', 'build/temp.macosx-10.9-x86_64-cpython-310/cmake-build-release', '--target', 'TopologicPythonBindings', '-v']
  [1/2] : && /Users/sahil/opt/anaconda3/envs/topologic_py310/bin/cmake -E rm -f TopologicCore/libTopologicCore.a && /Users/sahil/opt/anaconda3/envs/topologic_py310/bin/x86_64-apple-darwin13.4.0-ar qc TopologicCore/libTopologicCore.a  TopologicCore/CMakeFiles/TopologicCore.dir/src/About.cpp.o TopologicCore/CMakeFiles/TopologicCore.dir/src/Aperture.cpp.o TopologicCore/CMakeFiles/TopologicCore.dir/src/Cell.cpp.o TopologicCore/CMakeFiles/TopologicCore.dir/src/CellComplex.cpp.o TopologicCore/CMakeFiles/TopologicCore.dir/src/Cluster.cpp.o TopologicCore/CMakeFiles/TopologicCore.dir/src/ContentManager.cpp.o TopologicCore/CMakeFiles/TopologicCore.dir/src/Context.cpp.o TopologicCore/CMakeFiles/TopologicCore.dir/src/ContextManager.cpp.o TopologicCore/CMakeFiles/TopologicCore.dir/src/Dictionary.cpp.o TopologicCore/CMakeFiles/TopologicCore.dir/src/Edge.cpp.o TopologicCore/CMakeFiles/TopologicCore.dir/src/Face.cpp.o TopologicCore/CMakeFiles/TopologicCore.dir/src/GlobalCluster.cpp.o TopologicCore/CMakeFiles/TopologicCore.dir/src/Graph.cpp.o TopologicCore/CMakeFiles/TopologicCore.dir/src/InstanceGUIDManager.cpp.o TopologicCore/CMakeFiles/TopologicCore.dir/src/Shell.cpp.o TopologicCore/CMakeFiles/TopologicCore.dir/src/Topology.cpp.o TopologicCore/CMakeFiles/TopologicCore.dir/src/Utilities.cpp.o TopologicCore/CMakeFiles/TopologicCore.dir/src/Vertex.cpp.o TopologicCore/CMakeFiles/TopologicCore.dir/src/Wire.cpp.o TopologicCore/CMakeFiles/TopologicCore.dir/src/AttributeManager.cpp.o TopologicCore/CMakeFiles/TopologicCore.dir/src/DoubleAttribute.cpp.o TopologicCore/CMakeFiles/TopologicCore.dir/src/IntAttribute.cpp.o TopologicCore/CMakeFiles/TopologicCore.dir/src/ListAttribute.cpp.o TopologicCore/CMakeFiles/TopologicCore.dir/src/StringAttribute.cpp.o TopologicCore/CMakeFiles/TopologicCore.dir/src/ApertureFactory.cpp.o TopologicCore/CMakeFiles/TopologicCore.dir/src/CellComplexFactory.cpp.o TopologicCore/CMakeFiles/TopologicCore.dir/src/CellFactory.cpp.o TopologicCore/CMakeFiles/TopologicCore.dir/src/ClusterFactory.cpp.o TopologicCore/CMakeFiles/TopologicCore.dir/src/EdgeFactory.cpp.o TopologicCore/CMakeFiles/TopologicCore.dir/src/FaceFactory.cpp.o TopologicCore/CMakeFiles/TopologicCore.dir/src/ShellFactory.cpp.o TopologicCore/CMakeFiles/TopologicCore.dir/src/TopologyFactoryManager.cpp.o TopologicCore/CMakeFiles/TopologicCore.dir/src/VertexFactory.cpp.o TopologicCore/CMakeFiles/TopologicCore.dir/src/WireFactory.cpp.o TopologicCore/CMakeFiles/TopologicCore.dir/src/Geometry.cpp.o TopologicCore/CMakeFiles/TopologicCore.dir/src/Line.cpp.o TopologicCore/CMakeFiles/TopologicCore.dir/src/NurbsCurve.cpp.o TopologicCore/CMakeFiles/TopologicCore.dir/src/NurbsSurface.cpp.o TopologicCore/CMakeFiles/TopologicCore.dir/src/PlanarSurface.cpp.o TopologicCore/CMakeFiles/TopologicCore.dir/src/Surface.cpp.o TopologicCore/CMakeFiles/TopologicCore.dir/src/Bitwise.cpp.o TopologicCore/CMakeFiles/TopologicCore.dir/src/Utilities/CellUtility.cpp.o TopologicCore/CMakeFiles/TopologicCore.dir/src/Utilities/Direction.cpp.o TopologicCore/CMakeFiles/TopologicCore.dir/src/Utilities/EdgeUtility.cpp.o TopologicCore/CMakeFiles/TopologicCore.dir/src/Utilities/FaceUtility.cpp.o TopologicCore/CMakeFiles/TopologicCore.dir/src/Utilities/ShellUtility.cpp.o TopologicCore/CMakeFiles/TopologicCore.dir/src/Utilities/TopologyUtility.cpp.o TopologicCore/CMakeFiles/TopologicCore.dir/src/Utilities/TransformationMatrix2D.cpp.o TopologicCore/CMakeFiles/TopologicCore.dir/src/Utilities/Vector.cpp.o TopologicCore/CMakeFiles/TopologicCore.dir/src/Utilities/VertexUtility.cpp.o TopologicCore/CMakeFiles/TopologicCore.dir/src/Utilities/WireUtility.cpp.o && /Users/sahil/opt/anaconda3/envs/topologic_py310/bin/llvm-ranlib TopologicCore/libTopologicCore.a && /Users/sahil/opt/anaconda3/envs/topologic_py310/bin/cmake -E touch TopologicCore/libTopologicCore.a && :
  [2/2] : && /Users/sahil/opt/anaconda3/envs/topologic_py310/bin/x86_64-apple-darwin13.4.0-clang++ -march=core2 -mtune=haswell -mssse3 -ftree-vectorize -fPIC -fPIE -fstack-protector-strong -O2 -pipe -stdlib=libc++ -fvisibility-inlines-hidden -fmessage-length=0 -isystem /Users/sahil/opt/anaconda3/envs/topologic_py310/include -O3 -DNDEBUG -arch x86_64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk -bundle -Wl,-headerpad_max_install_names -Wl,-pie -Wl,-headerpad_max_install_names -Wl,-dead_strip_dylibs -Wl,-rpath,/Users/sahil/opt/anaconda3/envs/topologic_py310/lib -L/Users/sahil/opt/anaconda3/envs/topologic_py310/lib   -Xlinker -undefined -Xlinker dynamic_lookup -o TopologicPythonBindings/topologic.cpython-310-darwin.so TopologicPythonBindings/CMakeFiles/TopologicPythonBindings.dir/src/TopologicalQuery.cppwg.cpp.o TopologicPythonBindings/CMakeFiles/TopologicPythonBindings.dir/src/Topology.cppwg.cpp.o TopologicPythonBindings/CMakeFiles/TopologicPythonBindings.dir/src/Vertex.cppwg.cpp.o TopologicPythonBindings/CMakeFiles/TopologicPythonBindings.dir/src/Edge.cppwg.cpp.o TopologicPythonBindings/CMakeFiles/TopologicPythonBindings.dir/src/Wire.cppwg.cpp.o TopologicPythonBindings/CMakeFiles/TopologicPythonBindings.dir/src/Face.cppwg.cpp.o TopologicPythonBindings/CMakeFiles/TopologicPythonBindings.dir/src/Shell.cppwg.cpp.o TopologicPythonBindings/CMakeFiles/TopologicPythonBindings.dir/src/Cell.cppwg.cpp.o TopologicPythonBindings/CMakeFiles/TopologicPythonBindings.dir/src/CellComplex.cppwg.cpp.o TopologicPythonBindings/CMakeFiles/TopologicPythonBindings.dir/src/Cluster.cppwg.cpp.o TopologicPythonBindings/CMakeFiles/TopologicPythonBindings.dir/src/Aperture.cppwg.cpp.o TopologicPythonBindings/CMakeFiles/TopologicPythonBindings.dir/src/Graph.cppwg.cpp.o TopologicPythonBindings/CMakeFiles/TopologicPythonBindings.dir/src/Attribute.cppwg.cpp.o TopologicPythonBindings/CMakeFiles/TopologicPythonBindings.dir/src/Dictionary.cppwg.cpp.o TopologicPythonBindings/CMakeFiles/TopologicPythonBindings.dir/src/ContentManager.cppwg.cpp.o TopologicPythonBindings/CMakeFiles/TopologicPythonBindings.dir/src/Context.cppwg.cpp.o TopologicPythonBindings/CMakeFiles/TopologicPythonBindings.dir/src/IntAttribute.cppwg.cpp.o TopologicPythonBindings/CMakeFiles/TopologicPythonBindings.dir/src/StringAttribute.cppwg.cpp.o TopologicPythonBindings/CMakeFiles/TopologicPythonBindings.dir/src/DoubleAttribute.cppwg.cpp.o TopologicPythonBindings/CMakeFiles/TopologicPythonBindings.dir/src/ListAttribute.cppwg.cpp.o TopologicPythonBindings/CMakeFiles/TopologicPythonBindings.dir/src/VertexUtility.Binding.cpp.o TopologicPythonBindings/CMakeFiles/TopologicPythonBindings.dir/src/EdgeUtility.Binding.cpp.o TopologicPythonBindings/CMakeFiles/TopologicPythonBindings.dir/src/WireUtility.Binding.cpp.o TopologicPythonBindings/CMakeFiles/TopologicPythonBindings.dir/src/ShellUtility.Binding.cpp.o TopologicPythonBindings/CMakeFiles/TopologicPythonBindings.dir/src/CellUtility.Binding.cpp.o TopologicPythonBindings/CMakeFiles/TopologicPythonBindings.dir/src/TopologyUtility.Binding.cpp.o TopologicPythonBindings/CMakeFiles/TopologicPythonBindings.dir/src/FaceUtility.Binding.cpp.o TopologicPythonBindings/CMakeFiles/TopologicPythonBindings.dir/src/GlobalCluster.Binding.cpp.o TopologicPythonBindings/CMakeFiles/TopologicPythonBindings.dir/src/main.cpp.o  TopologicCore/libTopologicCore.a  /Users/sahil/opt/anaconda3/envs/topologic_py310/lib/libTKOffset.7.7.0.dylib  /Users/sahil/opt/anaconda3/envs/topologic_py310/lib/libTKMesh.7.7.0.dylib  /Users/sahil/opt/anaconda3/envs/topologic_py310/lib/libTKFillet.7.7.0.dylib  /Users/sahil/opt/anaconda3/envs/topologic_py310/lib/libTKBool.7.7.0.dylib  /Users/sahil/opt/anaconda3/envs/topologic_py310/lib/libTKBO.7.7.0.dylib  /Users/sahil/opt/anaconda3/envs/topologic_py310/lib/libTKPrim.7.7.0.dylib  /Users/sahil/opt/anaconda3/envs/topologic_py310/lib/libTKShHealing.7.7.0.dylib  /Users/sahil/opt/anaconda3/envs/topologic_py310/lib/libTKTopAlgo.7.7.0.dylib  /Users/sahil/opt/anaconda3/envs/topologic_py310/lib/libTKGeomAlgo.7.7.0.dylib  /Users/sahil/opt/anaconda3/envs/topologic_py310/lib/libTKBRep.7.7.0.dylib  /Users/sahil/opt/anaconda3/envs/topologic_py310/lib/libTKGeomBase.7.7.0.dylib  /Users/sahil/opt/anaconda3/envs/topologic_py310/lib/libTKG3d.7.7.0.dylib  /Users/sahil/opt/anaconda3/envs/topologic_py310/lib/libTKG2d.7.7.0.dylib  /Users/sahil/opt/anaconda3/envs/topologic_py310/lib/libTKMath.7.7.0.dylib  /Users/sahil/opt/anaconda3/envs/topologic_py310/lib/libTKernel.7.7.0.dylib && cd /Users/sahil/code/Topologic/TopologicPythonBindings/build/temp.macosx-10.9-x86_64-cpython-310/cmake-build-release/TopologicPythonBindings && /Users/sahil/opt/anaconda3/envs/topologic_py310/bin/llvm-strip -x /Users/sahil/code/Topologic/TopologicPythonBindings/build/temp.macosx-10.9-x86_64-cpython-310/cmake-build-release/TopologicPythonBindings/topologic.cpython-310-darwin.so
  ld: warning: -pie being ignored. It is only used when linking a main executable
  INFO:build:syscmd: running subprocess: ['cmake', '--install', 'build/temp.macosx-10.9-x86_64-cpython-310/cmake-build-release', '--prefix', 'build/temp.macosx-10.9-x86_64-cpython-310/cmake-install-release', '--component', 'TopologicPythonBindings']
  -- Install configuration: "Release"
  -- Installing: /Users/sahil/code/Topologic/TopologicPythonBindings/build/temp.macosx-10.9-x86_64-cpython-310/cmake-install-release/lib/TopologicPythonBindings/topologic.cpython-310-darwin.so
  /Users/sahil/opt/anaconda3/envs/topologic_py310/lib/python3.10/site-packages/setuptools/_distutils/cmd.py:66: SetuptoolsDeprecationWarning: setup.py install is deprecated.
  !!

          ********************************************************************************
          Please avoid running ``setup.py`` directly.
          Instead, use pypa/build, pypa/installer or other
          standards-based tools.

          See https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html for details.
          ********************************************************************************

  !!
    self.initialize_options()
  installing to build/bdist.macosx-10.9-x86_64/wheel
  running install
  running install_lib
  creating build/bdist.macosx-10.9-x86_64
  creating build/bdist.macosx-10.9-x86_64/wheel
  copying build/lib.macosx-10.9-x86_64-cpython-310/.DS_Store -> build/bdist.macosx-10.9-x86_64/wheel
  creating build/bdist.macosx-10.9-x86_64/wheel/topologic
  copying build/lib.macosx-10.9-x86_64-cpython-310/topologic/topologic.cpython-310-darwin.so -> build/bdist.macosx-10.9-x86_64/wheel/topologic
  copying build/lib.macosx-10.9-x86_64-cpython-310/topologic/__init__.py -> build/bdist.macosx-10.9-x86_64/wheel/topologic
  running install_egg_info
  running egg_info
  writing topologic.egg-info/PKG-INFO
  writing dependency_links to topologic.egg-info/dependency_links.txt
  writing top-level names to topologic.egg-info/top_level.txt
  reading manifest file 'topologic.egg-info/SOURCES.txt'
  writing manifest file 'topologic.egg-info/SOURCES.txt'
  Copying topologic.egg-info to build/bdist.macosx-10.9-x86_64/wheel/topologic-3.0.0-py3.10.egg-info
  running install_scripts
  [WARNING] This wheel needs a higher macOS version than the version your Python interpreter is compiled against.  To silence this warning, set MACOSX_DEPLOYMENT_TARGET to at least 13_0 or recreate these files with lower MACOSX_DEPLOYMENT_TARGET:
  build/bdist.macosx-10.9-x86_64/wheel/topologic/topologic.cpython-310-darwin.so[WARNING] This wheel needs a higher macOS version than the version your Python interpreter is compiled against.  To silence this warning, set MACOSX_DEPLOYMENT_TARGET to at least 13_0 or recreate these files with lower MACOSX_DEPLOYMENT_TARGET:
  build/bdist.macosx-10.9-x86_64/wheel/topologic/topologic.cpython-310-darwin.socreating build/bdist.macosx-10.9-x86_64/wheel/topologic-3.0.0.dist-info/WHEEL
  creating '/private/var/folders/jg/8nz0xtdx23x4l7fvjqkf0n5c0000gn/T/pip-wheel-500_8xv3/topologic-3.0.0-cp310-cp310-macosx_13_0_x86_64.whl' and adding 'build/bdist.macosx-10.9-x86_64/wheel' to it
  adding '.DS_Store'
  adding 'topologic/__init__.py'
  adding 'topologic/topologic.cpython-310-darwin.so'
  adding 'topologic-3.0.0.dist-info/METADATA'
  adding 'topologic-3.0.0.dist-info/WHEEL'
  adding 'topologic-3.0.0.dist-info/top_level.txt'
  adding 'topologic-3.0.0.dist-info/RECORD'
  removing build/bdist.macosx-10.9-x86_64/wheel
  Building wheel for topologic (setup.py) ... done
  Created wheel for topologic: filename=topologic-3.0.0-cp310-cp310-macosx_13_0_x86_64.whl size=673433 sha256=f7cfbd1e0fabe653598e403017a54fff78e1934d6051971105ed43034ba1f02a
  Stored in directory: /private/var/folders/jg/8nz0xtdx23x4l7fvjqkf0n5c0000gn/T/pip-ephem-wheel-cache-lofzh14a/wheels/f7/83/21/f169dde701e5e96c01ab7c78da56773fd6ffe58c16d059d312
Successfully built topologic
Traceback (most recent call last):
  File "/Users/sahil/code/Topologic/TopologicPythonBindings/build_macos.py", line 29, in <module>
    wheel = find_wheel(os.path.join(os.curdir, "dist"), "topologic")
  File "/Users/sahil/code/Topologic/TopologicPythonBindings/build_macos.py", line 17, in find_wheel
    raise FileNotFoundError(f"{wheel_pattern}")
FileNotFoundError: topologic-*-*310-*macosx_10_9_x86_64.whl
```

**Comment by wassimj** [comment]
Topologic has now been successfully built for MacOS Apple Silicon/ARM. The binaries are available through **_pip install topologicp_**y

**Comment by slavingia** [comment]
Thank you!
